[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"

[profile.release]
opt-level = 3
lto = true

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"
